# adct - CI Build
# https://github.com/ArtiomL/adct
# Artiom Lichtenstein
# v1.1.0, 10/01/2018

sudo: required

env:
  global:
    REPO=artioml/adct
    secure: "ajNtR+mlKxxF/RGUqbtm03VwxJZLAtSMPQ7oaCfx/Vrdx+Ir23ngs259ZLqjC/h8oXVTd3qmsJWoB8n9bk3kPD7AcfKgXTvQQgoX1D3xXcwuqKeUTwABC/jWt5MWvFnprwqM+CohyhNAS1sURQueZOiFhKKyJj2YdKO4nW5jxGt1PlaVhVDisj2r1XKjs64TTP+sshX0m2Dj7lF56umyht8QPWH5XxiSXPGcLgWyDsjCfAPddhDeNFPiKa+irk506FN8aBvCz0Vnm5kNnuM5Sww6u1Hg1XbU7XWZZKKqmrtsjmgbfG4HBaS63+5T0WDcRKjY+9n4LgWf/37gJg0IbrK93AzqfCOAnQBI8GVIAUQT6g0OGxFVDz2lBfIIrDHCkLCLushajimCE8VGAtk1cz6+x2QjrfL6KuI/w3kdm9QczP5MjbSTtlZjpbEyAfexkj6eDybXjptZk08sByI5pXH+b8DfFbBAYuywkgbAvQcEz5Kkue98SFZEiXPY0kDOgElh39EBHqj1/DC21sHh+oOU42iMGgwBtAgDzyjL2XomA3D1fwVA9eFJ2sNIwwPP2N+O29cDalnh3J+PIgj/KyiFTMUyBvWNI/lzkeF3KluL38TSxWXlOz2SWD5qtVRjsXtHZysQDXlPiB8NZl85NjqG5UWts/yu2gqCFtc10Aw="
    secure: "H+54+W+5lFOeBc9EOu8cwNHukto6GWFE/RrHa72jJWhau9i98Rzji5tFUnCFtgJCeCBmHuwZ7buB/jwsJAEY8KhzWkIxadhPftb4Ki6RptfBdWITJg9zBBsvUVz9t5RfA0l0uKNxh3RCQxRtsIkydM/395qUHkpUfZr2NAQkV07qWxq7+mCKBkV6hb7JqXoNC2bZWviTgIY6TIYjz+DdaRmYxig9Ikwvndx+NKcILUoj+aPylwClgCtMZvgxWqFO5EEUqlR2j5LiKpf3PUtNL3Lm33g1JGleWojJM6bkzW/8zmNmWtzeqUOICdt7HudQuLBl2t5Yni4Ao0i0YawwjazUDpUCZQTYY5bQ7nddqliiiMFDqEDbfgb0Lm0yX5g8mF00yk86GRcOGSTnAOHoshAA96oJGH8kLRsDBqgyng0fOXLV4qDdB7fouifSt4Po2KL8+JM+0mVysGf62XOR7X3Xetz8QXHy9xsvGsFaRHtM6EJhsFtEv8R1Wf9HNhdJYef7e8TwNmGLodC4mihWwa+HXzACYuLFPnCeLlUNG/7jSk89JKtBGNvSNvkNuZDKyhlLoydWC9k9KO4yaPxPoXC+NWaCrG38tSWz9S7gaJB/I5kS7Nh1IXB06vbQeAR73LRlLFNKVhj/wppOr/Px9oVd5MABg2HPKkOTg8u0JGI="

language: node_js
node_js:
  - "lts/*"

services:
  - docker

install:
  - npm install -g wscat3

script:
  - docker build -t $REPO .
  - cd ws
  - docker build -t $REPO:ws .
  - docker run -dit -p 80:8080 -p 443:8443 $REPO
  - docker run -dit -p 4433:4433 $REPO:ws
  - docker ps -a
  - curl -s http://127.0.0.1/uri$(shuf -i 0-1313 -n 1)/index.php | grep 'hello, world'
  - curl -sk https://127.0.0.1/uri$(shuf -i 0-1313 -n 1)/secure/index.php -u user:user | grep 'hello, user'
  - echo 'hello, world' | wscat -s echo ws://127.0.0.1:4433 | grep 'hello, world'

after_success:
  - docker images
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u $DOCKER_USER -p $DOCKER_PASS;
    docker push $REPO;
    docker push $REPO:ws;
    fi

notifications:
  slack:
    secure: "rZStkjLW9PYOuS1lYvNWTPPr1NvGQh0Myvah5eoLEuq+c1BAyis1IS629DbkjYsSssXUpS2tNTvDY1oQx4D9JMyFx9LrqmOqeao4p3vg2SPZKuCc8codxzBX2OyZ7t0kug6UgGTO2ChqqSKYq8bPCTn9Dnq8LmCP3f9eUQ+BVHYiaUU1OGhuH7QpH8MNHgurlZCk7a3mEez0nKMHHBD1yUgDe9vclZJ0DqN0G9lSrgwD2DhS9XWZ+Bo7J5K+OcbZMVhuErWWzkKdiN+Y/9ubMIYRB43u35oz0OGBEjIiPR9HROliMO0MESZe2h+l8ofC2W1Qi9k2Mytv2LYolKjZT5jNiLooD6r+nnKqPUj0FoLVgw56XZn+46Y4ajbLCsCS8mxabD4OXw4qMarTrnaps+hxo5dq6DaJW2Ackupsz/LIk9gcN7mDKn+SGHlGR+TGqcFgTbPDtSn34SbHC3TbB//Ul4B4An8RZdThJJNcv/yxQSIwxIRviHYIhYkgyRgqUrH2zGTVqh8AiPozCyjEDq2utbuF18deiLxVYMjM0IBNzoL550qE10evF7PeXWhoDQPS45Quy1oEvVqsY1fqxk94N3YN1vFHnflD3VLnU4r+44u4lGU3qRNE/2h6p/3Vx1fqE4Nqqcs74vxxs2WU/icCcoADGhN08+vdQhrnKq0="
